### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by lalit-lintel**

### CODE REVIEW

**Comment by lalit-lintel** [comment]
If possible please release a new version with the above changes.

**Comment by lalit-lintel** [comment]
@rohitchormale Can't we release master branch as a new version, like 0.0.2 or something else.
So we can directly install using pip.

**Comment by rohitchormale** [comment]
yes we can. But I need to check. As I remember, last release was done by @godsongera. Can you please reach out hime ?

**Comment by lalit-lintel** [comment]
Ok. Sure. 
Thanks for merge.

**Pull request merged**
